name: flutter_application_1
description: CatMe - Aplikasi Adopsi Kucing
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  intl: ^0.19.0
  crypto: ^3.0.3  
  sqflite: ^2.3.0 
  path: ^1.8.3 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/cat_icon.png